In [2]:
import pandas as pd
chipo = pd.read_csv("chipotle.csv")


#print(df)
pd.set_option("display.max_columns" , 5) #"??????"
print(chipo)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN     $2.39
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
3                                                   NaN     $2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[4622 rows x 5 columns]

In [3]:
chipo.head(4) # و اقدر احدد عاوزه اول كام row

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39

In [4]:
chipo.tail(4)

,order_id,quantity,item_name,choice_description,item_price
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [5]:
pd.set_option("display.max_columns" , 5) #  بيعرض الداتا ف شكل افضل و المفروص بعد ما اعملهل لوود تديني سوال يعبر عن كل عمود او صف 
pd.set_option("display.max_rows" ,5  ) 
# الكلام ده لو عندي schema csv file 
# عشان يفهمني لو في عمود مش فهمه بيعبر عن اي و هكذا

In [6]:
schema_df= pd.read_csv('chipotle.csv')

In [7]:
#Dictionary basics
# Creating data frame from dictionary

people = {
    "first": ["corey","jane","john"] ,
    "last" : ["schafer","doe","doe"] ,
    "email": ["coreyMschafer@gmail.com","janedoe@gmail.com","johndoe@gmail.com"]
}

In [8]:
people["email"]

['coreyMschafer@gmail.com', 'janedoe@gmail.com', 'johndoe@gmail.com']

In [9]:
df=pd.DataFrame(people)
df

   first     last                    email
0  corey  schafer  coreyMschafer@gmail.com
1   jane      doe        janedoe@gmail.com
2   john      doe        johndoe@gmail.com

In [10]:

# accessing a colunm of a dataframe
#دي افضل طريقه ااكسيس بيها علي عمود عشان لو اسم العمود متشابه مع اسم ميثود و استخدمت الدوت هيخلبط الدنيا

df["email"] 

# accessing multiple columns

df[["last",'email']]

      last                    email
0  schafer  coreyMschafer@gmail.com
1      doe        janedoe@gmail.com
2      doe        johndoe@gmail.com

In [11]:
# data frame :rows and columns , container of multiple series object
#series :rows of a single column

Filtration

In [12]:
# .iloc
"""
 .iloc : interger location ,an indexer for selecting rows by passing a
 a list of rows indecies and the outer list we can  add another lis for selecting specific cols

 iloc takes only numeric indexers
 """

""" 
.loc : similar as iloc but uses labels with indecies
"""
df.iloc[[0,1],[1,2]]

df.loc[[0,1],["email","last"]]

                     email     last
0  coreyMschafer@gmail.com  schafer
1        janedoe@gmail.com      doe

Sclicing

In [13]:
#Range of rows

#---------------------------------------------------
#error
#df.loc[[0:2],["email","last"]] 
#correction
df.loc[0:2,["email","last"]] 


"""Sclicing is inclusive"""

'Sclicing is inclusive'

In [14]:
"""Making first col the index of dataset"""

df.set_index("email" , inplace=True) # بس مش هتغير ف الداتا الاصليه الا اذا خليناها true

In [19]:
df

                     email  first     last
0  coreyMschafer@gmail.com  corey  schafer
1        janedoe@gmail.com   jane      doe
2        johndoe@gmail.com   john      doe

In [16]:
df.index

"""
now that the index is changed ,when using .loc it will be 
like so : df.loc['johndoe@gmail.com']
"""

"\nnow that the index is changed ,when using .loc it will be \nlike so : df.loc['johndoe@gmail.com']\n"

Reset the index

In [17]:
df.reset_index(inplace = True)
df

                     email  first     last
0  coreyMschafer@gmail.com  corey  schafer
1        janedoe@gmail.com   jane      doe
2        johndoe@gmail.com   john      doe

In [32]:
""" making a series of 2 cols"""

df["futt_name"] = df['first']+ " "+df["last"]

KeyError: 'last'

In [28]:
df

                     email  first      futt_name
0  coreyMschafer@gmail.com  corey  corey schafer
1        janedoe@gmail.com   jane       jane doe
2        johndoe@gmail.com   john       john doe

In [ ]:
""" Deleting columns """
df.drop(columns= ["last"] , inplace=True) # لو شغلت الامر مره مش ميرجع تاني لانو هيكون خلاص اتحذف 

""" be carefull """

' Deleting columns '

In [33]:
df['futt_name'].str.split(" " , expand = True) 
# expand will put splits in columns for each part

       0        1
0  corey  schafer
1   jane      doe
2   john      doe

In [34]:
df.drop(columns=['first'] , inplace=True)

In [35]:
df[['first' , 'last']]=df['futt_name'].str.split(" " , expand = True)

In [36]:
df

                     email      futt_name  first     last
0  coreyMschafer@gmail.com  corey schafer  corey  schafer
1        janedoe@gmail.com       jane doe   jane      doe
2        johndoe@gmail.com       john doe   john      doe

In [ ]:
#df.append({'first':'tony'}, ignore_index=True)
#append works with series not Data frame
# append is no longer available in pandas

#so insted i'll do this trick
new_row = pd.DataFrame([{'first':'gogo','last':'khaled'}])
pd.concat([df,new_row], ignore_index=True)

#عملت صف بنفس ستراكتشر الداتا و حطيته ف متغير و عملتلع concat مع df

                     email      futt_name  first     last
0  coreyMschafer@gmail.com  corey schafer  corey  schafer
1        janedoe@gmail.com       jane doe   jane      doe
2        johndoe@gmail.com       john doe   john      doe
3                      NaN            NaN   gogo   khaled

In [ ]:
""" .astype( )
بتحولي نوع البيانات للعمود تحفه"""


""" axis =1 -> col
    axis =0  -> row
    
 when using drop method axis 1 or 0 defines whether i want to
 apply the deletion  on cols or rows 
 
    
    
    
    """